In [1]:
# Data Manipulation with Pandas
import pandas as pd

# Create a sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Age': [25, 30, 35, 40, 45],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']
}

df = pd.DataFrame(data)

# Display the DataFrame
print("Original DataFrame:")
print(df)

Original DataFrame:
      Name  Age         City
0    Alice   25     New York
1      Bob   30  Los Angeles
2  Charlie   35      Chicago
3    David   40      Houston
4      Eve   45      Phoenix

In [8]:
sales_df = pd.read_csv('sales_data_practice.csv')

# Display the first few rows of the sales DataFrame
print("\nSales DataFrame:")
print(sales_df.head())

Sales DataFrame:
         Date     Product     Category  Price  Quantity_Sold   Region
0  2024-01-01      Laptop  Electronics   1200              5   Berlin
1  2024-01-02       Phone  Electronics    800             10   Munich
2  2024-01-03      Tablet  Electronics    400              7  Hamburg
3  2024-01-04  Headphones  Electronics    150             15   Berlin
4  2024-01-05     Monitor  Electronics    300              6  Cologne

In [9]:
# describbe the sales DataFrame
print("\nSales DataFrame Description:")
print(sales_df.describe())

Sales DataFrame Description:
             Price  Quantity_Sold
count    30.000000      30.000000
mean    570.000000       9.466667
std     388.098814       2.635740
min     150.000000       5.000000
25%     300.000000       7.250000
50%     400.000000       9.000000
75%     800.000000      11.000000
max    1200.000000      15.000000

In [10]:
# Datatypes of the sales DataFrame
print("\nSales DataFrame Datatypes:")
print(sales_df.dtypes)

Sales DataFrame Datatypes:
Date               str
Product            str
Category           str
Price            int64
Quantity_Sold    int64
Region             str
dtype: object

In [11]:
## Handling Missing Values
# Check for missing values in the sales DataFrame
print("\nMissing Values in Sales DataFrame:")
print(sales_df.isnull().sum())

Missing Values in Sales DataFrame:
Date             0
Product          0
Category         0
Price            0
Quantity_Sold    0
Region           0
dtype: int64

In [12]:
# head of the sales DataFrame
print("\nHead of Sales DataFrame:")
print(sales_df.head())

Head of Sales DataFrame:
         Date     Product     Category  Price  Quantity_Sold   Region
0  2024-01-01      Laptop  Electronics   1200              5   Berlin
1  2024-01-02       Phone  Electronics    800             10   Munich
2  2024-01-03      Tablet  Electronics    400              7  Hamburg
3  2024-01-04  Headphones  Electronics    150             15   Berlin
4  2024-01-05     Monitor  Electronics    300              6  Cologne

In [13]:
# fill missing values with 0
sales_df_filled = sales_df.fillna(0)
print("\nSales DataFrame with Missing Values Filled:")
print(sales_df_filled.head())

Sales DataFrame with Missing Values Filled:
         Date     Product     Category  Price  Quantity_Sold   Region
0  2024-01-01      Laptop  Electronics   1200              5   Berlin
1  2024-01-02       Phone  Electronics    800             10   Munich
2  2024-01-03      Tablet  Electronics    400              7  Hamburg
3  2024-01-04  Headphones  Electronics    150             15   Berlin
4  2024-01-05     Monitor  Electronics    300              6  Cologne

In [16]:
# filling missing values with mean of the column
sales_df['sales_filled_mean'] = sales_df['Price'].fillna(sales_df['Price'].mean())
print("\nSales DataFrame with Missing Values Filled with Mean:")
print(sales_df.head())

Sales DataFrame with Missing Values Filled with Mean:
         Date     Product     Category  Price  Quantity_Sold   Region  \
0  2024-01-01      Laptop  Electronics   1200              5   Berlin
1  2024-01-02       Phone  Electronics    800             10   Munich
2  2024-01-03      Tablet  Electronics    400              7  Hamburg
3  2024-01-04  Headphones  Electronics    150             15   Berlin
4  2024-01-05     Monitor  Electronics    300              6  Cologne

   sales_filled_mean
0               1200
1                800
2                400
3                150
4                300

In [18]:
sales_df.dtypes

Date                   str
Product                str
Category               str
Price                int64
Quantity_Sold        int64
Region                 str
sales_filled_mean    int64
dtype: object

In [19]:
# Renaming columns
sales_df.rename(columns={'Price': 'Unit_Price'}, inplace=True)
print("\nSales DataFrame with Renamed Columns:")
print(sales_df.head())

Sales DataFrame with Renamed Columns:
         Date     Product     Category  Unit_Price  Quantity_Sold   Region  \
0  2024-01-01      Laptop  Electronics        1200              5   Berlin
1  2024-01-02       Phone  Electronics         800             10   Munich
2  2024-01-03      Tablet  Electronics         400              7  Hamburg
3  2024-01-04  Headphones  Electronics         150             15   Berlin
4  2024-01-05     Monitor  Electronics         300              6  Cologne

   sales_filled_mean
0               1200
1                800
2                400
3                150
4                300

In [21]:
# change datatype of 'Unit_Price' column to float
sales_df['Unit_Price'] = sales_df['Unit_Price'].astype(float)
print("\nSales DataFrame with 'Unit_Price' Column as Float:")
print(sales_df.dtypes)

Sales DataFrame with 'Unit_Price' Column as Float:
Date                     str
Product                  str
Category                 str
Unit_Price           float64
Quantity_Sold          int64
Region                   str
sales_filled_mean      int64
dtype: object

In [23]:
sales_df['Price'] = sales_df['Unit_Price'] * 3

In [24]:
# data Aggregation and Grouping

# Grouping by 'Category' and calculating the mean of 'Price'
category_mean = sales_df.groupby('Category')['Price'].mean()
print("\nMean Price by Category:")
print(category_mean)

Mean Price by Category:
Category
Electronics    1710.0
Name: Price, dtype: float64

In [26]:
# Grouping by two categorical columns and calculating the sum of 'Price'
category_product_sum = sales_df.groupby(['Category', 'Product'])['Price'].sum()
print("\nSum of Price by Category and Product:")
print(category_product_sum)

Sum of Price by Category and Product:
Category     Product
Electronics  Headphones     2700.0
             Laptop        21600.0
             Monitor        5400.0
             Phone         14400.0
             Tablet         7200.0
Name: Price, dtype: float64

In [28]:
# aggregate multiple functions on a column
category_agg = sales_df.groupby('Product')['Price'].agg(['mean', 'sum', 'count'])
print("\nAggregated Price by Product:")
print(category_agg)

Aggregated Price by Product:
              mean      sum  count
Product
Headphones   450.0   2700.0      6
Laptop      3600.0  21600.0      6
Monitor      900.0   5400.0      6
Phone       2400.0  14400.0      6
Tablet      1200.0   7200.0      6

In [31]:
## Merging and Joining DataFrames
# Create another DataFrame to merge with sales_df
data2 = {
    'Product': ['A', 'B', 'C', 'D', 'E'],
    'Category': ['X', 'Y', 'X', 'Y', 'X'],
    'Stock': [100, 150, 200, 250, 300]
}
data2_df = pd.DataFrame(data2)

# Merge sales_df with data2_df on 'Product' and 'Category'
merged = pd.merge(sales_df, data2_df, on=['Product', 'Category'], how='left')
print("\nMerged DataFrame:")
print(merged.head())

Merged DataFrame:
         Date     Product     Category  Unit_Price  Quantity_Sold   Region  \
0  2024-01-01      Laptop  Electronics      1200.0              5   Berlin
1  2024-01-02       Phone  Electronics       800.0             10   Munich
2  2024-01-03      Tablet  Electronics       400.0              7  Hamburg
3  2024-01-04  Headphones  Electronics       150.0             15   Berlin
4  2024-01-05     Monitor  Electronics       300.0              6  Cologne

   sales_filled_mean   Price  Stock
0               1200  3600.0    NaN
1                800  2400.0    NaN
2                400  1200.0    NaN
3                150   450.0    NaN
4                300   900.0    NaN

In [32]:
pd.merge(sales_df, data2_df, on=['Product', 'Category'], how='inner')

Empty DataFrame
Columns: [Date, Product, Category, Unit_Price, Quantity_Sold, Region, sales_filled_mean, Price, Stock]
Index: []

In [33]:
pd.merge(sales_df, data2_df, on=['Product', 'Category'], how='outer')

,Date,Product,Category,Unit_Price,Quantity_Sold,Region,sales_filled_mean,Price,Stock
0,NaN,A,X,NaN,NaN,NaN,NaN,NaN,100.0
1,NaN,B,Y,NaN,NaN,NaN,NaN,NaN,150.0
2,NaN,C,X,NaN,NaN,NaN,NaN,NaN,200.0
3,NaN,D,Y,NaN,NaN,NaN,NaN,NaN,250.0
4,NaN,E,X,NaN,NaN,NaN,NaN,NaN,300.0
5,2024-01-04,Headphones,Electronics,150.0,15.0,Berlin,150.0,450.0,NaN
6,2024-01-09,Headphones,Electronics,150.0,14.0,Berlin,150.0,450.0,NaN
7,2024-01-14,Headphones,Electronics,150.0,13.0,Berlin,150.0,450.0,NaN
8,2024-01-19,Headphones,Electronics,150.0,12.0,Berlin,150.0,450.0,NaN
9,2024-01-24,Headphones,Electronics,150.0,10.0,Berlin,150.0,450.0,NaN
10,2024-01-29,Headphones,Electronics,150.0,11.0,Berlin,150.0,450.0,NaN
11,2024-01-01,Laptop,Electronics,1200.0,5.0,Berlin,1200.0,3600.0,NaN
12,2024-01-06,Laptop,Electronics,1200.0,8.0,Berlin,1200.0,3600.0,NaN
13,2024-01-11,Laptop,Electronics,1200.0,6.0,Berlin,1200.0,3600.0,NaN
14,2024-01-16,Laptop,Electronics,1200.0,9.0,Berlin,1200.0,3600.0,NaN
15,2024-01-21,Laptop,Electronics,1200.0,7.0,Berlin,1200.0,3600.0,NaN
16,2024-01-26,Laptop,Electronics,1200.0,12.0,Berlin,1200.0,3600.0,NaN
17,2024-01-05,Monitor,Electronics,300.0,6.0,Cologne,300.0,900.0,NaN
18,2024-01-10,Monitor,Electronics,300.0,10.0,Cologne,300.0,900.0,NaN
19,2024-01-15,Monitor,Electronics,300.0,7.0,Cologne,300.0,900.0,NaN
20,2024-01-20,Monitor,Electronics,300.0,8.0,Cologne,300.0,900.0,NaN
21,2024-01-25,Monitor,Electronics,300.0,8.0,Cologne,300.0,900.0,NaN
22,2024-01-30,Monitor,Electronics,300.0,7.0,Cologne,300.0,900.0,NaN
23,2024-01-02,Phone,Electronics,800.0,10.0,Munich,800.0,2400.0,NaN
24,2024-01-07,Phone,Electronics,800.0,12.0,Munich,800.0,2400.0,NaN
25,2024-01-12,Phone,Electronics,800.0,11.0,Munich,800.0,2400.0,NaN
26,2024-01-17,Phone,Electronics,800.0,10.0,Munich,800.0,2400.0,NaN
27,2024-01-22,Phone,Electronics,800.0,9.0,Munich,800.0,2400.0,NaN
28,2024-01-27,Phone,Electronics,800.0,9.0,Munich,800.0,2400.0,NaN
29,2024-01-03,Tablet,Electronics,400.0,7.0,Hamburg,400.0,1200.0,NaN
30,2024-01-08,Tablet,Electronics,400.0,9.0,Hamburg,400.0,1200.0,NaN
31,2024-01-13,Tablet,Electronics,400.0,8.0,Hamburg,400.0,1200.0,NaN
32,2024-01-18,Tablet,Electronics,400.0,6.0,Hamburg,400.0,1200.0,NaN
33,2024-01-23,Tablet,Electronics,400.0,11.0,Hamburg,400.0,1200.0,NaN
34,2024-01-28,Tablet,Electronics,400.0,14.0,Hamburg,400.0,1200.0,NaN

In [34]:
pd.merge(sales_df, data2_df, on=['Product', 'Category'], how='left')

,Date,Product,Category,Unit_Price,Quantity_Sold,Region,sales_filled_mean,Price,Stock
0,2024-01-01,Laptop,Electronics,1200.0,5,Berlin,1200,3600.0,NaN
1,2024-01-02,Phone,Electronics,800.0,10,Munich,800,2400.0,NaN
2,2024-01-03,Tablet,Electronics,400.0,7,Hamburg,400,1200.0,NaN
3,2024-01-04,Headphones,Electronics,150.0,15,Berlin,150,450.0,NaN
4,2024-01-05,Monitor,Electronics,300.0,6,Cologne,300,900.0,NaN
5,2024-01-06,Laptop,Electronics,1200.0,8,Berlin,1200,3600.0,NaN
6,2024-01-07,Phone,Electronics,800.0,12,Munich,800,2400.0,NaN
7,2024-01-08,Tablet,Electronics,400.0,9,Hamburg,400,1200.0,NaN
8,2024-01-09,Headphones,Electronics,150.0,14,Berlin,150,450.0,NaN
9,2024-01-10,Monitor,Electronics,300.0,10,Cologne,300,900.0,NaN
10,2024-01-11,Laptop,Electronics,1200.0,6,Berlin,1200,3600.0,NaN
11,2024-01-12,Phone,Electronics,800.0,11,Munich,800,2400.0,NaN
12,2024-01-13,Tablet,Electronics,400.0,8,Hamburg,400,1200.0,NaN
13,2024-01-14,Headphones,Electronics,150.0,13,Berlin,150,450.0,NaN
14,2024-01-15,Monitor,Electronics,300.0,7,Cologne,300,900.0,NaN
15,2024-01-16,Laptop,Electronics,1200.0,9,Berlin,1200,3600.0,NaN
16,2024-01-17,Phone,Electronics,800.0,10,Munich,800,2400.0,NaN
17,2024-01-18,Tablet,Electronics,400.0,6,Hamburg,400,1200.0,NaN
18,2024-01-19,Headphones,Electronics,150.0,12,Berlin,150,450.0,NaN
19,2024-01-20,Monitor,Electronics,300.0,8,Cologne,300,900.0,NaN
20,2024-01-21,Laptop,Electronics,1200.0,7,Berlin,1200,3600.0,NaN
21,2024-01-22,Phone,Electronics,800.0,9,Munich,800,2400.0,NaN
22,2024-01-23,Tablet,Electronics,400.0,11,Hamburg,400,1200.0,NaN
23,2024-01-24,Headphones,Electronics,150.0,10,Berlin,150,450.0,NaN
24,2024-01-25,Monitor,Electronics,300.0,8,Cologne,300,900.0,NaN
25,2024-01-26,Laptop,Electronics,1200.0,12,Berlin,1200,3600.0,NaN
26,2024-01-27,Phone,Electronics,800.0,9,Munich,800,2400.0,NaN
27,2024-01-28,Tablet,Electronics,400.0,14,Hamburg,400,1200.0,NaN
28,2024-01-29,Headphones,Electronics,150.0,11,Berlin,150,450.0,NaN
29,2024-01-30,Monitor,Electronics,300.0,7,Cologne,300,900.0,NaN

In [35]:
pd.merge(sales_df, data2_df, on=['Product', 'Category'], how='right')

,Date,Product,Category,Unit_Price,Quantity_Sold,Region,sales_filled_mean,Price,Stock
0,NaN,A,X,NaN,NaN,NaN,NaN,NaN,100
1,NaN,B,Y,NaN,NaN,NaN,NaN,NaN,150
2,NaN,C,X,NaN,NaN,NaN,NaN,NaN,200
3,NaN,D,Y,NaN,NaN,NaN,NaN,NaN,250
4,NaN,E,X,NaN,NaN,NaN,NaN,NaN,300