In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [35]:
df = pd.read_excel('flight_price.xlsx')
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [36]:
df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
10678,Air Asia,9/04/2019,Kolkata,Banglore,CCU → BLR,19:55,22:25,2h 30m,non-stop,No info,4107
10679,Air India,27/04/2019,Kolkata,Banglore,CCU → BLR,20:45,23:20,2h 35m,non-stop,No info,4145
10680,Jet Airways,27/04/2019,Banglore,Delhi,BLR → DEL,08:20,11:20,3h,non-stop,No info,7229
10681,Vistara,01/03/2019,Banglore,New Delhi,BLR → DEL,11:30,14:10,2h 40m,non-stop,No info,12648
10682,Air India,9/05/2019,Delhi,Cochin,DEL → GOI → BOM → COK,10:55,19:15,8h 20m,2 stops,No info,11753

In [37]:
## Get the basic information about the dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Date_of_Journey  10683 non-null  str
 2   Source           10683 non-null  str
 3   Destination      10683 non-null  str
 4   Route            10682 non-null  str
 5   Dep_Time         10683 non-null  str
 6   Arrival_Time     10683 non-null  str
 7   Duration         10683 non-null  str
 8   Total_Stops      10682 non-null  str
 9   Additional_Info  10683 non-null  str
 10  Price            10683 non-null  int64
dtypes: int64(1), str(10)
memory usage: 918.2 KB

In [38]:
df.describe()

              Price
count  10683.000000
mean    9087.064121
std     4611.359167
min     1759.000000
25%     5277.000000
50%     8372.000000
75%    12373.000000
max    79512.000000

In [39]:
# handling date of journey
df['Date_of_Journey'] = pd.to_datetime(df['Date_of_Journey'], format='%d/%m/%Y')
df['Day'] = df['Date_of_Journey'].dt.day.astype(int)
df['Month'] = df['Date_of_Journey'].dt.month.astype(int)
df['Year'] = df['Date_of_Journey'].dt.year.astype(int)
df.drop('Date_of_Journey', axis=1, inplace=True)

In [40]:
# handling arrival time

df['Arrival_Time'] = pd.to_datetime(df['Arrival_Time'].apply(lambda x: x.split(' ')[0]), format='%H:%M')
df['Arrival_Hour'] = df['Arrival_Time'].dt.hour.astype(int)
df['Arrival_Minute'] = df['Arrival_Time'].dt.minute.astype(int)
df.drop('Arrival_Time', axis=1, inplace=True)

In [41]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          10683 non-null  str
 1   Source           10683 non-null  str
 2   Destination      10683 non-null  str
 3   Route            10682 non-null  str
 4   Dep_Time         10683 non-null  str
 5   Duration         10683 non-null  str
 6   Total_Stops      10682 non-null  str
 7   Additional_Info  10683 non-null  str
 8   Price            10683 non-null  int64
 9   Day              10683 non-null  int64
 10  Month            10683 non-null  int64
 11  Year             10683 non-null  int64
 12  Arrival_Hour     10683 non-null  int64
 13  Arrival_Minute   10683 non-null  int64
dtypes: int64(6), str(8)
memory usage: 1.1 MB

In [42]:
df.head()

,Airline,Source,Destination,Route,Dep_Time,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,2h 50m,non-stop,No info,3897,24,3,2019,1,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,7h 25m,2 stops,No info,7662,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,19h,2 stops,No info,13882,9,6,2019,4,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,5h 25m,1 stop,No info,6218,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,4h 45m,1 stop,No info,13302,1,3,2019,21,35

In [43]:
# handle departure time
df['Dep_Time'] = pd.to_datetime(df['Dep_Time'], format='%H:%M')
df['Dep_Hour'] = df['Dep_Time'].dt.hour.astype(int)
df['Dep_Minute'] = df['Dep_Time'].dt.minute.astype(int)
df.drop('Dep_Time', axis=1, inplace=True)

In [44]:
df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Minute
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897,24,3,2019,1,10,22,20
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662,1,5,2019,13,15,5,50
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882,9,6,2019,4,25,9,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218,12,5,2019,23,30,18,5
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302,1,3,2019,21,35,16,50

In [45]:
# Convert duration to minutes
def convert_duration_to_minutes(duration):
    duration = duration.strip()
    if 'h' in duration and 'm' in duration:
        hours, minutes = duration.split('h')
        minutes = minutes.replace('m', '').strip()
        return int(hours) * 60 + int(minutes)
    elif 'h' in duration:
        hours = duration.replace('h', '').strip()
        return int(hours) * 60
    elif 'm' in duration:
        minutes = duration.replace('m', '').strip()
        return int(minutes)
    else:
        return 0

df['Duration_in_Minutes'] = df['Duration'].apply(convert_duration_to_minutes).astype(int)
df.drop('Duration', axis=1, inplace=True)

In [46]:
df.head(2)

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Minute,Duration_in_Minutes
0,IndiGo,Banglore,New Delhi,BLR → DEL,non-stop,No info,3897,24,3,2019,1,10,22,20,170
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2 stops,No info,7662,1,5,2019,13,15,5,50,445

In [49]:
df['Total_Stops'].unique()

<StringArray>
['non-stop', '2 stops', '1 stop', '3 stops', nan, '4 stops']
Length: 6, dtype: str

In [51]:
df['Total_Stops'].isnull().sum()

np.int64(1)

In [52]:
df['Total_Stops'] = df['Total_Stops'].map({'non-stop': 0, '1 stop': 1, '2 stops': 2, '3 stops': 3, '4 stops': 4, np.nan: 1})

In [53]:
df['Total_Stops'].isnull().sum()

np.int64(0)

In [54]:
df.head(2)

,Airline,Source,Destination,Route,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Minute,Duration_in_Minutes
0,IndiGo,Banglore,New Delhi,BLR → DEL,0,No info,3897,24,3,2019,1,10,22,20,170
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,2,No info,7662,1,5,2019,13,15,5,50,445

In [55]:
df.drop(['Route'], axis=1, inplace=True)

In [56]:
df.head(2)

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Minute,Duration_in_Minutes
0,IndiGo,Banglore,New Delhi,0,No info,3897,24,3,2019,1,10,22,20,170
1,Air India,Kolkata,Banglore,2,No info,7662,1,5,2019,13,15,5,50,445

In [59]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
encoded_cols = encoder.fit_transform(df[['Airline', 'Source', 'Destination']]).toarray()
encoded_df = pd.DataFrame(encoded_cols, columns=encoder.get_feature_names_out(['Airline', 'Source', 'Destination']))
df = pd.concat([df, encoded_df], axis=1)
df.drop(['Airline', 'Source', 'Destination'], axis=1, inplace=True)

In [60]:
df.head()

,Total_Stops,Additional_Info,Price,Day,Month,Year,Arrival_Hour,Arrival_Minute,Dep_Hour,Dep_Minute,...,Source_Chennai,Source_Delhi,Source_Kolkata,Source_Mumbai,Destination_Banglore,Destination_Cochin,Destination_Delhi,Destination_Hyderabad,Destination_Kolkata,Destination_New Delhi
0,0,No info,3897,24,3,2019,1,10,22,20,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,2,No info,7662,1,5,2019,13,15,5,50,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,2,No info,13882,9,6,2019,4,25,9,25,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,1,No info,6218,12,5,2019,23,30,18,5,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,1,No info,13302,1,3,2019,21,35,16,50,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [61]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10683 entries, 0 to 10682
Data columns (total 34 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   Total_Stops                                10683 non-null  int64
 1   Additional_Info                            10683 non-null  str
 2   Price                                      10683 non-null  int64
 3   Day                                        10683 non-null  int64
 4   Month                                      10683 non-null  int64
 5   Year                                       10683 non-null  int64
 6   Arrival_Hour                               10683 non-null  int64
 7   Arrival_Minute                             10683 non-null  int64
 8   Dep_Hour                                   10683 non-null  int64
 9   Dep_Minute                                 10683 non-null  int64
 10  Duration_in_Minutes                        10683 non-null  int64
 11  Airline_Air Asia                           10683 non-null  float64
 12  Airline_Air India                          10683 non-null  float64
 13  Airline_GoAir                              10683 non-null  float64
 14  Airline_IndiGo                             10683 non-null  float64
 15  Airline_Jet Airways                        10683 non-null  float64
 16  Airline_Jet Airways Business               10683 non-null  float64
 17  Airline_Multiple carriers                  10683 non-null  float64
 18  Airline_Multiple carriers Premium economy  10683 non-null  float64
 19  Airline_SpiceJet                           10683 non-null  float64
 20  Airline_Trujet                             10683 non-null  float64
 21  Airline_Vistara                            10683 non-null  float64
 22  Airline_Vistara Premium economy            10683 non-null  float64
 23  Source_Banglore                            10683 non-null  float64
 24  Source_Chennai                             10683 non-null  float64
 25  Source_Delhi                               10683 non-null  float64
 26  Source_Kolkata                             10683 non-null  float64
 27  Source_Mumbai                              10683 non-null  float64
 28  Destination_Banglore                       10683 non-null  float64
 29  Destination_Cochin                         10683 non-null  float64
 30  Destination_Delhi                          10683 non-null  float64
 31  Destination_Hyderabad                      10683 non-null  float64
 32  Destination_Kolkata                        10683 non-null  float64
 33  Destination_New Delhi                      10683 non-null  float64
dtypes: float64(23), int64(10), str(1)
memory usage: 2.8 MB