In [1]:
# Data Encoding
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

In [2]:
## Create a dataframe

df = pd.DataFrame({
    'color': ['red', 'blue', 'green', 'red', 'blue']
})

In [3]:
df.head()

   color
0    red
1   blue
2  green
3    red
4   blue

In [4]:
# Create an instance of OneHotEncoder
encoder = OneHotEncoder()

In [5]:
# perform fit and transform
encoded_data = encoder.fit_transform(df[['color']]).toarray()

In [6]:
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out())

In [7]:
encoded_df.head()

   color_blue  color_green  color_red
0         0.0          0.0        1.0
1         1.0          0.0        0.0
2         0.0          1.0        0.0
3         0.0          0.0        1.0
4         1.0          0.0        0.0

In [8]:
# for new data
encoder.transform([['red']]).toarray()

/home/prateek/da_bootcamp/python/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

array([[0., 0., 1.]])

In [9]:
pd.concat([df, encoded_df], axis=1)

   color  color_blue  color_green  color_red
0    red         0.0          0.0        1.0
1   blue         1.0          0.0        0.0
2  green         0.0          1.0        0.0
3    red         0.0          0.0        1.0
4   blue         1.0          0.0        0.0

In [11]:
import seaborn as sns
df_tips = sns.load_dataset('tips')

In [12]:
# Label Encoding

df_tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [13]:
df_tips['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, str): ['Thur', 'Fri', 'Sat', 'Sun']

In [15]:
# Labelencoder
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df_tips['day_encoded'] = label_encoder.fit_transform(df_tips['day'])
df_tips['day_encoded'].unique()

array([2, 1, 3, 0])

In [29]:
df_tips[['day_encoded', 'day']]

     day_encoded   day
0              2   Sun
1              2   Sun
2              2   Sun
3              2   Sun
4              2   Sun
..           ...   ...
239            1   Sat
240            1   Sat
241            1   Sat
242            1   Sat
243            3  Thur

[244 rows x 2 columns]

In [30]:
# Ordinal Encoding

from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()

df_ordinal = pd.DataFrame({
    'size': ['small', 'medium', 'large', 'medium', 'small']
})

In [31]:
# Create an instance of OrdinalEncoder
ordinal_encoder = OrdinalEncoder(categories=[['small', 'medium', 'large']])

# perform fit and transform
ordinal_encoded_data = ordinal_encoder.fit_transform(df_ordinal[['size']])

ordinal_encoded_df = pd.DataFrame(ordinal_encoded_data, columns=ordinal_encoder.get_feature_names_out())
ordinal_encoded_df.head()

   size
0   0.0
1   1.0
2   2.0
3   1.0
4   0.0

In [32]:
# Target guided ordinal encoding
df = pd.DataFrame({
    'city': ['A', 'B', 'C', 'D', 'D', 'C', 'A', 'A'],
    'price': [100, 150, 200, 250, 300, 350, 400, 450]
})

target_mean = df.groupby('city')['price'].mean().sort_values()

In [33]:
df['city_encoded'] = df['city'].map(target_mean)

In [34]:
df[['price', 'city_encoded']]

   price  city_encoded
0    100    316.666667
1    150    150.000000
2    200    275.000000
3    250    275.000000
4    300    275.000000
5    350    275.000000
6    400    316.666667
7    450    316.666667

In [41]:
import seaborn as sns
tips_data = sns.load_dataset('tips')

In [53]:
tips_data.head()

   total_bill   tip     sex smoker  day    time  size time_encoded
0       16.99  1.01  Female     No  Sun  Dinner     2    20.797159
1       10.34  1.66    Male     No  Sun  Dinner     3    20.797159
2       21.01  3.50    Male     No  Sun  Dinner     3    20.797159
3       23.68  3.31    Male     No  Sun  Dinner     2    20.797159
4       24.59  3.61  Female     No  Sun  Dinner     4    20.797159

In [54]:
tips_data['time'].unique()

['Dinner', 'Lunch']
Categories (2, str): ['Lunch', 'Dinner']

In [55]:
tips_target_mean = tips_data.groupby('time')['total_bill'].mean()

In [56]:
tips_data['time_encoded'] = tips_data['time'].map(tips_target_mean)

In [57]:
tips_data[['time', 'time_encoded']].drop_duplicates()

      time time_encoded
0   Dinner    20.797159
77   Lunch    17.168676

In [ ]:
tips_data['time_encoded'].unique()

# Shows dinner is more expensive than lunch
# This is a very simple encoding technique but it can be very powerful. 
# It can capture the relationship between the categorical variable and the target variable. 
# However, it can also lead to overfitting if there are too many categories or if the relationship is not strong enough.

[20.797159, 17.168676]
Categories (2, float64): [17.168676, 20.797159]

In [72]:
lunch_count = (tips_data['time'] == 'Lunch').sum()
dinner_count = (tips_data['time'] == 'Dinner').sum()

print(f'Lunch count: {lunch_count}')
print(f'Dinner count: {dinner_count}')

Lunch count: 68
Dinner count: 176

In [79]:
import seaborn as sns
tips_data = sns.load_dataset('tips')

In [83]:
tips_majority = tips_data[tips_data['time'] == 'Dinner']
tips_minority = tips_data[tips_data['time'] == 'Lunch']

tips_minority_upsampled = tips_minority.sample(n=len(tips_majority), replace=True, random_state=42)
tips_upsampled = pd.concat([tips_majority, tips_minority_upsampled])

tips_upsampled['time'].value_counts()

time
Lunch     176
Dinner    176
Name: count, dtype: int64

In [84]:
tips_target_mean = tips_upsampled.groupby('time')['total_bill'].mean()

In [85]:
tips_upsampled['time_encoded'] = tips_upsampled['time'].map(tips_target_mean)

In [88]:
tips_upsampled[['time', 'time_encoded']].drop_duplicates()

# This is a simple example of how to handle imbalanced data using upsampling. 
# We have two classes: Lunch and Dinner. Dinner is the majority class and Lunch is the minority class. We upsample the minority class by randomly sampling with replacement until we have the same number of samples in both classes.
#  Then we perform target guided ordinal encoding on the upsampled data.

# We find that the mean total bill for Lunch is 17.28 and for Dinner is 20.80.
#  This shows that Dinner is more expensive than Lunch on average.

       time time_encoded
0    Dinner    20.797159
196   Lunch    17.272614